name: Build2

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # This is needed to be able to run ./gradlew below
      # You can run `git update-index --chmod +x gradlew` then remove this step.
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Publish
        id: publish
        if: ${{ steps.version.outputs.result != 'alpha' && success() }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: HpFUWlWM
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          curseforge-id: 1090298
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          name: TerraFirmaCraft 1.21.1-${{ steps.version.outputs.result }}
          version: ${{ steps.version.outputs.result }}
          version-type: ${{ steps.version_type.outputs.result }}
          java: 21
          loaders: |
            neoforge

          changelog-file: CHANGELOG.md
